### ISSUE TITLE
Failed on run npm run e22

### ISSUE THREAD

**Issue by mr-mateus** [builtbyjay/ngapimock-test#1]
Log

C:\workspace\ngapimock-test>npm run e2e

> ng-apimock-test@0.0.0 e2e C:\workspace\ngapimock-test
> ng e2e  --proxy-config proxy.conf.json

** NG Live Development Server is running on http://localhost:49157 **
 10% building modules 3/3 modules 0 active[HPM] Proxy created: /api  ->  http://localhost:3000
[HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
(node:9484) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Hash: 30b2a94b6b58b74288f2
Time: 7868ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 158 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 7.08 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 9.89 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 3.54 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
webpack: Compiled successfully.
[15:14:36] I/update - chromedriver: file exists C:\workspace\ngapimock-test\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.26win32.zip
[15:14:36] I/update - chromedriver: unzipping chromedriver_2.26win32.zip
[15:14:37] I/update - chromedriver: 2.26 up to date
[15:14:37] I/direct - Using ChromeDriver directly...
[15:14:37] I/launcher - Running 1 instances of WebDriver

DevTools listening on ws://127.0.0.1:12383/devtools/browser/e69b734a-de3c-4da2-a69e-01a5276302bd
Spec started
[HPM] GET /api/quote-overview -> http://localhost:3000

  ng-apimock-test App
    × should display one instalment
      - Expected 3 to equal 1.
          at Object.<anonymous> (C:\workspace\ngapimock-test\e2e\app.e2e-spec.ts:15:43)
          at new ManagedPromise (C:\workspace\ngapimock-test\node_modules\selenium-webdriver\lib\promise.js:1067:7)
          at TaskQueue.execute_ (C:\workspace\ngapimock-test\node_modules\selenium-webdriver\lib\promise.js:2970:14)
          at TaskQueue.executeNext_ (C:\workspace\ngapimock-test\node_modules\selenium-webdriver\lib\promise.js:2953:27)
          at asyncRun (C:\workspace\ngapimock-test\node_modules\selenium-webdriver\lib\promise.js:2860:25)
          at C:\workspace\ngapimock-test\node_modules\selenium-webdriver\lib\promise.js:676:7
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
[HPM] GET /api/quote-overview -> http://localhost:3000
    √ should display three instalments
[HPM] GET /api/quote-overview -> http://localhost:3000
    √ should display six instalments
[HPM] GET /api/quote-overview -> http://localhost:3000
    √ should show an error

**************************************************
*                    Failures                    *
**************************************************

1) ng-apimock-test App should display one instalment
  - Expected 3 to equal 1.

Executed 4 of 4 specs (1 FAILED) in 2 secs.
[15:14:42] I/launcher - 0 instance(s) of WebDriver still running
[15:14:42] I/launcher - chrome #01 failed 1 test(s)
[15:14:42] I/launcher - overall: 1 failed spec(s)
[15:14:42] E/launcher - Process exited with error code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ng-apimock-test@0.0.0 e2e: `ng e2e  --proxy-config proxy.conf.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng-apimock-test@0.0.0 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mateus.leal\AppData\Roaming\npm-cache\_logs\2017-11-28T17_14_42_362Z-debug.log

could you give me some help please?

**Comment by builtbyjay** [comment]
Sorry for the late response.

When you use the `selectScenario` method within your e2e tests, a PUT request should be made to the server running your mocks (typically on port 3000). Unfortunately, the URL of the request is incorrect and is using the NG live dev server port (typically something like 49152).

An easy solution is to add a rule to the proxy config to send all requests to `/ngapimock/*` to port 3000.

You can see the changes necessary in this commit: https://github.com/builtbyjay/ngapimock-test/commit/2afe86655f997fbec29f92a446cde5dc4bc51ffd
